server:
  port: 8081

cookorgo-service:
  host: localhost
  port: 8080

auth-service:
  host: localhost
  port: 8085

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: cookorgo
          uri: http://${cookorgo-service.host}:${cookorgo-service.port}/
          predicates:
            - Path=/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka